[package]
name = "grad"
version = "0.1.0"
authors = ["Geoffroy Couprie <contact@geoffroycouprie.com>"]

[dependencies]
nom = "^4.0"
log = "^0.4"
warp = "^0.1"
time = "^0.1"
bytes = "^0.4"
serde = "^1.0"
tokio = "^0.1"
tokio-io = "^0.1"
serde_derive = "^1.0"
pretty_env_logger = "^0.2"
